services:
  app:
    container_name: "users-app"
    build: ./users
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/users
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: "users-db"
    restart: always
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - ./users/.docker/dbdata:/var/lib/postgres/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: "kafka"
    restart: always
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: "zookeeper"
    hostname: zookeeper
    restart: always
    ports:
      - '2181:2181'
    environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000