services:
  api-gateway:
    container_name: "api-gateway"
    build: ./api_gateway
    ports:
      - '8080:8080'
    depends_on:
      - users
      - notifications
    environment:
      SPRING_APPLICATION_NAME: api-gateway

  users:
    container_name: "users-service"
    build: ./users
    ports:
      - '8081:8081'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://users-db:5432/users
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - users-db
      - kafka

  users-db:
    image: postgres:latest
    container_name: "users-db"
    restart: always
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - ./users/.docker/dbdata:/var/lib/postgres/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: users

  notifications:
    container_name: "notifications-service"
    build: ./notifications
    ports:
      - '8082:8082'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://notifications-db:5432/notifications
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - notifications-db
      - kafka

  notifications-db:
    image: postgres:latest
    container_name: "notifications-db"
    restart: always
    tty: true
    ports:
      - '5433:5432'
    volumes:
      - ./notifications/.docker/dbdata:/var/lib/postgres/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: notifications

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: "kafka"
    restart: always
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://kafka:9092,PLAINTEXT_EXTERNAL://localhost:29092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: "zookeeper"
    hostname: zookeeper
    restart: always
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000