spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}
      expiration: 1
    refresh-token:
      expiration: 12


logging:
  level:
    org:
      springframework:
        security: DEBUG