spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/users}
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

api:
  security:
    access-token:
      secret: ${JWT_SECRET:my-secret-token-key}
      expiration: 1
    refresh-token:
      secret: ${JWT_SECRET:my-secret-refresh-token-key}
      expiration: 12

springdoc:
  swagger-ui:
    path: /swagger-ui
    title: Users API
