spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
api:
  security:
    access-token:
      secret: ${JWT_SECRET:my-secret-token-key}
      expiration: 1
    refresh-token:
      secret: ${JWT_SECRET:my-secret-refresh-token-key}
      expiration: 12

springdoc:
  swagger-ui:
    path: /swagger-ui
    title: Users API
