services:
#  app:
#    container_name: "users-app"
#    build: .
#    ports:
#      - '8080:8080'
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/users
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root
#    depends_on:
#      - db
  db:
    image: postgres:latest
    container_name: "users-db"
    restart: always
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgres/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
